### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by TheMTtakeover** [TheMTtakeover/goat-rulings#3]
Add a toggle to site to allow the option to switch to dark mode

**Comment by TheMTtakeover** [comment]
This feature is being worked on for v1.10

**Comment by jenzhng** [comment]
Hi, can I work on this?

**Comment by TheMTtakeover** [comment]
> Hi, can I work on this?

Yeah. Any help would be appreciated.

In terms of ideas I was hoping that the current dark theme could be the default and then there could be a button or some sort of toggle to switch to a light theme. Ideally it would also save current theme and keep the current theme the whole way across the site.

**Comment by TheMTtakeover** [comment]
Working code submitted by kathiria@

Pending pull request merge
